sudo: required

branches:
  only:
    - master

services:
  - docker

language: generic

stages:
  - name: build

jobs:
  include:
    - stage: build
      name: datadog-agent-extras
      script:
        - make build tag
      deploy:
        provider: script
        script: make login push
        on:
          branch: master
