---
name: Continuous Deployment

on:
  push:
    branches:
    - master
    paths:
    - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Build Docker image
        run: make build
      
      - name: Tag image
        run: make tag
      
      - name: Push image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make push
