---
name: Continuous Deployment

on:
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Build Docker image
        run: make build
      
      - name: Tag image
        run: make tag
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make login
      
      - name: Push image
        run: make push
